# Generated by Django 4.1.5 on 2023-01-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=200)),
                ('long_desc', models.CharField(max_length=3000)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('movie_url', models.URLField(max_length=500)),
            ],
        ),
    ]
