# Generated by Django 4.1.5 on 2023-01-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='short_desc',
            field=models.CharField(max_length=500),
        ),
    ]
