# Generated by Django 4.1.5 on 2023-01-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movies_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
